config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home' => 'homes#home'

  resources :forms do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :storylines do
    resources :talks
    get 'add_user' => 'storylines#add_user_view'
    post 'add_user' => 'storylines#add_user'
  end
end

app/models/storyline.rb
class Storyline < ApplicationRecord
  has_many :talks, dependent: :destroy
  has_many :talkrooms, dependent: :destroy
  has_many :users, through: :talkrooms
  has_many :tags, dependent: :destroy
  mount_uploader :image, ImageUploader
  after_create_commit { StorylineBroadcastJob.perform_later self }
  after_update_commit { StorylineBroadcastJob.perform_later self }
  after_destroy_commit { StorylineBroadcastJob.perform_later self }
end

app/controllers/storylines_controller.rb
class StorylinesController < ApplicationController
  def new
    @post = Storyline.new
  end

  def create
    @post = Storyline.new(create_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
      StorylineBroadcastJob.perform_later(@post, 'create')
      Talkroom.create(storyline_id: @post.id, user_id: current_user.id)
      redirect_to storyline_path(@post.id)
    else
      # Output errors for debugging purposes
      puts @post.errors.full_messages

      # Handle the case where the object is not valid and rendering the form again
      render :new
    end

  end

  def index
    @post = Storyline.all
    @posts = Storyline.page(params[:page]).reverse_order
  end

  def show
    storyline = Storyline.find(params[:id])
    if storyline.private == true
      if storyline.users.include?(current_user)
        @user = storyline.users
        @post = Storyline.find(params[:id])
        @comments = Talk.where(storyline_id: params[:id])
      else
        redirect_to "/storylines"
      end
    else
      @user = storyline.users
      @post = Storyline.find(params[:id])
      @comments = Talk.where(storyline_id: params[:id])
    end

  end

  def edit
    if current_user.id == Storyline.find(params[:id]).user_id
      # トークルームに所属しているユーザーを返す
      @post = Storyline.find(params[:id])
      @user = @post.users
    else
      redirect_to "/storylines/#{params[:id]}"
    end
  end

  def update
    @post = Storyline.find(params[:id])
    @post.update(create_params)
    StorylineBroadcastJob.perform_later(@post, 'update')
    redirect_to storyline_path(@post.id)
  end

  def destroy
    post = Storyline.find(params[:id])
    post.destroy
    StorylineBroadcastJob.perform_later(post, 'update')
    redirect_to '/storylines'
  end

  def add_user_view
    @post = Storyline.find(params[:storyline_id])
    @user = current_user.followers
    @users = @post.users
    @add_user = AddUser.new
  end

  def add_user
    users = params.require(:add_user)
    users.each do |key, value|
      if users[key] == "0" && Storyline.find(params[:storyline_id]).users.include?(User.find(key))
        Storyline.find(params[:storyline_id]).users.delete(User.find(key))
      elsif users[key] == "1" && !Storyline.find(params[:storyline_id]).users.include?(User.find(key))
        Storyline.find(params[:storyline_id]).users << User.find(key)

      end
    end
    redirect_to "/storylines/#{params[:storyline_id]}"

  end

  private

  def create_params
    params.require(:storyline).permit(:title, :subject, :image, :user_id, :private)
  end

end

app/helpers/storylines_helper.rb
module StorylinesHelper
end

app/views/storylines/add_user_view.html.erb
<% if @user.exists? %>
  <%= form_with model: @add_user, url: "/storylines/#{@post.id}/add_user", local: true do |f| %>
    <% @user.each do |user| %>
      <%= f.label user.name %>>
      <!-- チェックされていたらそのユーザーのidを変数に入れる-->
      <% if @users.include?(user) %>>
        <%= f.check_box user.id, checked: true %>
      <% else %>
        <%= f.check_box user.id, checked: false %>
      <% end %>>
    <% end %>
    <%= f.submit "追加する" %>
  <% end %>

<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/storylines/edit.html.erb
<head>
  <!--javascript new_preview.jsの読み込み-->
  <%= javascript_include_tag 'new_preview' %>
</head>
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">ルームを編集</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @post, url: "/storylines/#{@post.id}", data: { behavior: "storyline_speaker" }, local: true do |f| %>
        <div class="form-group">
          <label class="form-label">タイトル</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">内容</label>
          <%= f.text_area :subject, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">タグ</label>
          <%= f.text_field :tags, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">画像</label><br>
          <%= f.label :image %>
          <%= f.file_field :image, id: "imageInput" %><!--サムネ画像アップロード-->

          <div class="preview" id="imagePreview">
            <% if f.file_field :image == nil %>
              <% if @post.image? %>
                <p>
                  <%= image_tag @post.image.url %><!--アップロードした画像を表示 -->
                </p>
              <% else %>
                <img alt="" src="">
              <% end %>
            <% else %>
              <img alt="" src="">
            <% end %>
          </div>
          </div>
          <div class="form-group">
            <label class="form-label">private</label>
            <!-- チェックボックスで真偽を返す -->
            <%= f.check_box :private, class: "form-control", :as => :boolean %>
          </div>
          <!-- 提出する -->
          　　　
          <div class="form-group">
            <%= f.submit "作成", class: "btn btn-primary" %> <!-- 提出ボタン -->
      <% end %>
      <% if @post.private == true %>
        <%= link_to "AddUsers", "/storylines/#{@post.id}/add_user" %>
      <% end %>
      <%= link_to "削除", "/storylines/#{@post.id}", data: { turbo: true, turbo_method: :delete } %>
      </div>
      </div>
    </div>
  </div>

app/views/storylines/index.html.erb
<div id ='storylines'>
</div>
<div class="cover-index">
  <div class="container">
    <div class="row">
      <h1 class="fw-normal  d-flex justify-content-center mt-3">トークルーム一覧</h1>
    </div>
    <div class="row">
      <% @posts.each do |post| %>
        <% if post.private == true %>
          <% next %>
        <% end %>
        <div class="col-lg-4 col-md-6">
          <div class="one-post d-flex justify-content-around">
              <div class="card my-3"  style="width: 18rem; height: 15rem;">
                <p class="caption  card-title d-flex justify-content-around"><%= link_to post.title, "/storylines/#{post.id}", data: { turbo: false }%></p>
                <% if post.image? %>  <!-- アップロード画像がある場合に実行する -->
                  <div class="caption">
                    <%= image_tag post.image.half.url, class: "card-img img-fluid" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                  </div>
                <% end %>
                <p class="caption text-truncate"><%= post.subject %></p>
              </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>

app/views/storylines/new.html.erb
<head>
  <!--javascript new_preview.jsの読み込み-->
  <%= javascript_include_tag 'new_preview'%>
</head>
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">ルームを作る</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @post, url: '/storylines', local: true do |f| %>
        <div class="form-group">
          <label class="form-label">タイトル</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">内容</label>
          <%= f.text_area :subject, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">画像</label><br>
          <%= f.label :image %>
          <%= f.file_field :image,id:"imageInput"  %>
          <div class="preview" id="imagePreview">
            <img  alt="" src="">
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">private</label>
          <!-- チェックボックスで真偽を返す -->
          <%= f.check_box :private, class: "form-control", :as => :boolean %>
        </div>
        <!-- 提出する -->
      
        <div class="form-group">
          <%= f.submit "作成", class: "btn btn-primary" %> <!-- 提出ボタン-->
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/storylines/show.html.erb
<div class="cover-index">
  <div class="container">
    <div class="row">
      <h1 class="fw-bold mt-3 d-flex justify-content-center"><%= @post.title %></h1>
    </div>
    <div class="row">
        <% if @post.image? %>  <!-- アップロード画像がある場合に実行する -->
          <p>
            <%= image_tag @post.image.half.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
          </p>
        <% end %>
        <p class="caption d-flex justify-content-center"><%= @post.subject %></p>

          <!-- チャットメッセージ表示用のコンテナ -->
          <div id="talks-container" class="container-fluid">
            <!-- チャットメッセージ -->
            <div id="talks" class="row">
              <%= render @comments %>
            </div>
          </div>

        <div class="cover-new">
          <div class="container">
            <div class="row justify-content-center">
              <h1 class="font-weight-normal mt-3">Comment</h1>
            </div>
            <div class="row justify-content-center">
              <%= form_with model: Talk.new, url: "/storylines/#{@post.id}/talks", local: true,id: 'your-form-id' do |f| %>
                <div class="form-group">
                  <label class="form-label">内容</label>
                  <%= f.text_field :message, rows: 10, class: "form-control" %>
                </div>
                <div class="form-group">
                  <label class="form-label">画像</label><br>
                  <%= f.label :image %>
                  <%= f.file_field :image %>
                  <% if @post.image? %>  <!-- アップロード画像がある場合に実行する -->
                    <p>
                      <%= image_tag @post.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
                    </p>
                  <% end %>
                </div>
                <%= f.submit '投稿する', class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        </div>


        <%= link_to "Addcomment", new_storyline_talk_path(@post.id) %>
        <% if @post.user_id == current_user.id %>
          <%= link_to "編集", edit_storyline_path(@post.id),data: { Turbo: false }%>
        <% end %>
      </div>
      <% if @post.private == true %>
        <% if @user != nil %>
          <% @user.each do |user| %>
            <table>
              <td><%= user.name %></td>
              <% if user.profile_image_id? %>
                <%= image_tag user.profile_image_id.half.url %>
              <% end %>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
            </table>
          <% end %>
        <% else %>
          <p>ユーザーはいません</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>