config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home' => 'homes#home'

  resources :forms do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :storylines do
    resources :talks
    get 'add_user' => 'storylines#add_user_view'
    post 'add_user' => 'storylines#add_user'
  end
end

app/models/add_user.rb
class AddUser
  # モデルの機能を使えるようにします
  include ActiveModel::Model
  # 要素を定義します

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true # この行を追記
  belongs_to :post, optional: true # この行を追記
  validates :comment, presence: true, length: { maximum: 35 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  after_create_commit { FormBroadcastJob.perform_later self }
  after_destroy_commit { FormBroadcastJob.perform_later self }
  # belongs_to :post_image,optional: true
  #
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many_attached :image do |attachable|
    attachable.variant :half, resize_to_limit: [256, 256]
  end
  validates :title, presence: true, length: { maximum: 15 }
  validates :text, presence: true, length: { maximum: 195 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, optional: true, class_name: "User"
  belongs_to :followed, optional: true, class_name: "User"

end

app/models/storyline.rb
class Storyline < ApplicationRecord
  has_many :talks, dependent: :destroy
  has_many :talkrooms, dependent: :destroy
  has_many :users, through: :talkrooms
  has_many :tags, dependent: :destroy
  mount_uploader :image, ImageUploader
  after_create_commit { StorylineBroadcastJob.perform_later self }
  after_update_commit { StorylineBroadcastJob.perform_later self }
  after_destroy_commit { StorylineBroadcastJob.perform_later self }
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :storyline, optional: true
  belongs_to :user, optional: true
end

app/models/talk.rb
class Talk < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  belongs_to :storyline, optional: true
  after_create_commit { TalkBroadcastJob.perform_later self }
  after_update_commit { TalkBroadcastJob.perform_later self }
  after_destroy_commit { TalkBroadcastJob.perform_later self }
end

app/models/talkroom.rb
class Talkroom < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :storyline, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :storylines, dependent: :destroy
  has_many :talks, dependent: :destroy
  has_many :talkrooms, dependent: :destroy
  has_many :storylines, through: :talkrooms
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  mount_uploader :profile_image_id, ImageUploader

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    puts @post
    @post.user = current_user
    if @post.save
      redirect_to form_path(@post.id)
    else
      render :new
    end
  end

  def index
    @post = Post.new
    @posts=Post.all.reverse_order
    #@posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new # この行を追記
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    if current_user.id == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
    else
      redirect_to "/forms/#{params[:id]}"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to form_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to '/forms'
  end

  def default_url
    'sample.jpg'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image_id, :image_id_cache, :user_id,image: [])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def home
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def new
    @post = Talk.new

  end

  def create

    @post = Talk.new(create_params)
    @post.user = current_user
    @post.storyline_id = (params[:storyline_id])
    @post.save
    TalkBroadcastJob.perform_later(@post, 'create')
    #redirect_to storyline_path(@post.storyline_id)
  end

  def index
    @posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Storyline.find(params[:id])
  end

  def edit
    if current_user.id == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
    else
      redirect_to "/forms/#{params[:id]}"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      TalkBroadcastJob.perform_later(@post, 'update')
      redirect_to form_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    TalkBroadcastJob.perform_later(post, 'update')
    redirect_to '/forms'
  end

  def default_url
    'sample.jpg'
  end

  private

  def create_params
    params.require(:talk).permit(:message, :mention_user, :image, :storyline_id, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(3).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    if current_user.id == params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def follows
    user = User.find(params[:id])
    @users = user.follower.page(params[:page]).per(3).reverse_order
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower_user.page(params[:page]).per(3).reverse_order
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/storylines_helper.rb
module StorylinesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/talks/_talk.html.erb
<div class="talk" id="talk-<%= talk.id %>">
  <p>

    <p><%=talk.user.name%></p>

    <div class="one-post">

      <% if talk.image? %>  <!-- アップロード画像がある場合に実行する -->
        <p>
          <%= image_tag talk.image.half.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
        </p>
      <% end %>
    </div>
    <p><%= talk.message %></p>
    </div>

app/views/talks/new.html.erb
<div class="cover-new">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-3">Comment</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: Talk.new, url: "/storylines/#{params[:storyline_id]}/talks", local: true do |f| %>
        <div class="form-group">
          <label class="form-label">内容</label>
          <%= f.text_field :message, rows: 10, class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">画像</label><br>
          <%= f.label :image %>
          <%= f.file_field :image %>
          <% if @post.image? %>  <!-- アップロード画像がある場合に実行する -->
            <p>
              <%= image_tag @post.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
            </p>
          <% end %>
        </div>
        <%= f.submit '投稿する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">プロフィール編集</h1>
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label class="form-label">名前</label>
          <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "名前", class: "form-control" %>
        </div>
        <div class="form-group">
          <label class="form-label">プロフィール画像</label><br>
          <% if @user.profile_image_id? %>  <!-- アップロード画像がある場合に実行する -->
            <p>
              <%= image_tag @user.profile_image_id.half.url, class: "mb-3 profile-img" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
            </p>
          <% end %>
          <%= f.label :profile_image_id, placeholder: "プロフィール画像" %>
          <%= f.file_field :profile_image_id %>
        </div>
        <div class="form-group">
          <label class="form-label">プロフィール</label>
          <%= f.text_field :profile, class: "form-control" %><br>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row">
      <h1 class="fw-normal mt-5 mb-5 d-flex justify-content-center">ユーザー一覧</h1>
    </div>
    <div class="row justify-content-center">
      <% @users.each do |user| %>
        <div class="one-post card w-100">
          <%= link_to user_path(user) do %>
            <p class="caption h4"><%= user.name %></p>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container">
    <div class="row">
        <% if user_signed_in? && @user == current_user %>
          <h1 class="d-flex justify-content-center display-2 mt-5 mb-5">マイページ</h1>
        <% else %>
          <h1 class="d-flex justify-content-center display-2 fw-nomal mt-5 mb-5" >
          <%= @user.name%>
          </h1>
        <% end %>
    </div>
    <div class="row">
        <div class="col d-flex flex-column justify-content-center">
          <% if @user.profile_image_id? %>  <!-- アップロード画像がある場合に実行する -->
            <p class="d-flex justify-content-center">
              <%= image_tag @user.profile_image_id.half.url, class: "my-3 profile-img" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
            </p>
          <% end %>
        </div>
        <div class="col d-flex flex-column justify-content-center">
          <div class="ml-2 mb-2 card w-100" style="width: 40%;">
            <div class="d-flex justify-content-center h2 lh-sm"><%= @user.profile%></div>
          </div>
        </div>
    </div>

    <div class="row">
        <% if user_signed_in? && @user == current_user %>
        <div class="col-6 d-flex justify-content-center">
          <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn  btn-outline-dark " %>
        </div>
        <% end %>

        <% if current_user != @user %>
              <div class="col-6  d-flex justify-content-center">
        <% if current_user.following?(@user) %>
                <%= link_to 'フォロー外す', user_relationships_path(@user.id), data: { turbo: true, turbo_method: :delete }, class: "btn btn-sm btn-danger" %>
        <% else %>
                <%= link_to 'フォローする', user_relationships_path(@user.id), data: { turbo: true, turbo_method: :post }, class: "btn btn-sm btn-success" %>
        <% end %>
              </div>
        <% end %>
        
          <div class="col-6 d-flex justify-content-evenly">          
          <%= link_to "follow:#{@user.followings.count}", " /users/#{@user.id}/followings", class: "btn btn-sm btn-danger" %>
          <%= link_to "follower:#{@user.followers.count}", " /users/#{@user.id}/followers",  class: "btn btn-sm btn-danger" %>
          </div>
  </div>

  <div class="row">
      <% @posts.each do |post| %>
        <div class="col-lg-4 col-md-6 d-flex justify-content-around my-3">
          <div class=" one-post" style="width: 20rem; height: 24rem;">
            <div class="card text-white bg-info">
              <p class="caption card-title"><%= post.user.name %></p>
              <p class="caption text-center card-title"><%= link_to post.title, "/forms/#{post.id} " %></p>
              <% if post.image_id? %>  <!-- アップロード画像がある場合に実行する -->
                <%= image_tag post.image_id.half.url, class: "card-img w-100" ,style: "width: 20rem; height: 11.375rem;"%><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
              <% end %>
              <p class="caption text-truncate"><%= post.text %></p>
              <p class="caption"><%= "#{post.comments.count} コメント" %></p>
              <p class="caption">
                <%= render post%>
              </p>
            </div>
          </div>
        </div>
      <% end %>
      <%#= paginate @posts %>
    </div>
</div>
</div>