config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'home' => 'homes#home'

  resources :forms do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :storylines do
    resources :talks
    get 'add_user' => 'storylines#add_user_view'
    post 'add_user' => 'storylines#add_user'
  end
end

app/models/add_user.rb
class AddUser
  # モデルの機能を使えるようにします
  include ActiveModel::Model
  # 要素を定義します

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true # この行を追記
  belongs_to :post, optional: true # この行を追記
  validates :comment, presence: true, length: { maximum: 35 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  after_create_commit { FormBroadcastJob.perform_later self }
  after_destroy_commit { FormBroadcastJob.perform_later self }
  # belongs_to :post_image,optional: true
  #
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many_attached :image do |attachable|
    attachable.variant :half, resize_to_limit: [256, 256]
  end
  validates :title, presence: true, length: { maximum: 15 }
  validates :text, presence: true, length: { maximum: 195 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, optional: true, class_name: "User"
  belongs_to :followed, optional: true, class_name: "User"

end

app/models/storyline.rb
class Storyline < ApplicationRecord
  has_many :talks, dependent: :destroy
  has_many :talkrooms, dependent: :destroy
  has_many :users, through: :talkrooms
  has_many :tags, dependent: :destroy
  mount_uploader :image, ImageUploader
  after_create_commit { StorylineBroadcastJob.perform_later self }
  after_update_commit { StorylineBroadcastJob.perform_later self }
  after_destroy_commit { StorylineBroadcastJob.perform_later self }
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :storyline, optional: true
  belongs_to :user, optional: true
end

app/models/talk.rb
class Talk < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  belongs_to :storyline, optional: true
  after_create_commit { TalkBroadcastJob.perform_later self }
  after_update_commit { TalkBroadcastJob.perform_later self }
  after_destroy_commit { TalkBroadcastJob.perform_later self }
end

app/models/talkroom.rb
class Talkroom < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :storyline, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :storylines, dependent: :destroy
  has_many :talks, dependent: :destroy
  has_many :talkrooms, dependent: :destroy
  has_many :storylines, through: :talkrooms
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  mount_uploader :profile_image_id, ImageUploader

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    puts @post
    @post.user = current_user
    if @post.save
      redirect_to form_path(@post.id)
    else
      render :new
    end
  end

  def index
    @post = Post.new
    @posts=Post.all.reverse_order
    #@posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new # この行を追記
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    if current_user.id == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
    else
      redirect_to "/forms/#{params[:id]}"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to form_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to '/forms'
  end

  def default_url
    'sample.jpg'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image_id, :image_id_cache, :user_id,image: [])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def home
  end

end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def new
    @post = Talk.new

  end

  def create

    @post = Talk.new(create_params)
    @post.user = current_user
    @post.storyline_id = (params[:storyline_id])
    @post.save
    TalkBroadcastJob.perform_later(@post, 'create')
    #redirect_to storyline_path(@post.storyline_id)
  end

  def index
    @posts = Post.page(params[:page]).reverse_order
  end

  def show
    @post = Storyline.find(params[:id])
  end

  def edit
    if current_user.id == Post.find(params[:id]).user_id
      @post = Post.find(params[:id])
    else
      redirect_to "/forms/#{params[:id]}"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      TalkBroadcastJob.perform_later(@post, 'update')
      redirect_to form_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    TalkBroadcastJob.perform_later(post, 'update')
    redirect_to '/forms'
  end

  def default_url
    'sample.jpg'
  end

  private

  def create_params
    params.require(:talk).permit(:message, :mention_user, :image, :storyline_id, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/storylines_helper.rb
module StorylinesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/_form.html.erb
<div class="post" id="post-<%= post.id %>">
<% if post.favorited_by?(current_user) %>
  <%= button_to form_favorites_path(post), method: :delete, class: "favorite_btn" do %>
    ♥<%= post.favorites.count %> いいね
  <% end %>
<% else %>
  <%= button_to form_favorites_path(post), data: { turbo: true, turbo_method: :post },class: "favorite_btn" do %>
    ♡<%= post.favorites.count %> いいね
  <% end %>
<% end %>
</div>

app/views/forms/_new.html.erb
<head>
  <!--javascript new_preview.jsの読み込み-->
<%= javascript_include_tag 'new_preview'%>

</head>
<div class="cover-new">
  <div class="container ">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <h1 class="fw-bold my-3">新規投稿</h1>
      </div>
    </div>

      <div class="row">
        <%= form_with model: post, url: '/forms', local: true do |f| %>
          <div class="col">
            <label class="form-label fs-3 my-3">タイトル(15文字まで)</label>
            <%= f.text_field :title, class: "form-control form-control-lg" %>
          </div>
        </div>

          <div class="row">
            <div class="col fs-3">
              <label class="form-label my-3">画像</label>
              <br>
              <%= f.label :image %>
              <br>
              <%= f.file_field :image,id:"imageInput", class:"btn btn-secondary w-100",multiple:true%>
              <div class="preview" id="imagePreview">
              </div>
            </div>
          </div>

        <div class="row">
          <div class="col">
            <label class="form-label fs-3 my-3">内容(195文字まで)</label>
            <%= f.text_area :text, rows: 10, class: "form-control" %>
          </div>
        </div>

          <div class="row">
            <div class="my-3 d-flex justify-content-end">
              <%= f.submit '投稿する', class: "btn btn-primary btn-outline-light btn-lg" %>
            </div>
          </div>
        <% end %>
  </div>
</div>

app/views/forms/edit.html.erb
<head>
  <!--javascript new_preview.jsの読み込み-->
  <%= javascript_include_tag 'new_preview'%>
</head>

<div class="cover-edit"><!--投稿を編集-->
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="font-weight-normal mt-5 mb-5">投稿編集</h1><!--ページのタイトルを表示-->
    </div>
    <div class="row justify-content-center">
      <%= form_with model: @post, url: "/forms/#{@post.id}", local: true do |f| %><!--無視-->
        <div class="form-group">
          <label class="form-label">タイトル</label>
          <%= f.text_field :title, class: "form-control" %>　<!--投稿タイトル入力-->
        </div>
        <div class="form-group">
          <label class="form-label">内容</label>
          <%= f.text_area :text, rows: 10, class: "form-control" %><!--投稿内容入力-->
        </div>
        <div class="form-group">
          <label class="form-label">画像</label><br>
          <%= f.hidden_field :image_id_cache %>
          <%= f.file_field :image_id,id:"imageInput"%><!--サムネ画像アップロード-->

          <div class="preview" id="imagePreview">
            <%if f.file_field :image_id==nil%>
              <%if @post.image_id?%>
                <p>
                  <%= image_tag @post.image_id.url %><!--アップロードした画像を表示 -->
                </p>
              <%else%>
                <img  alt="" src="">
              <%end%>
            <%else%>
              <img  alt="" src="">
            <%end%>
          </div>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %><br>　<!--保存ボタン-->
        <%= link_to '投稿詳細ページへ', "/forms/#{@post.id}", class: "btn btn-dark mt-3" %><!--投稿詳細にページ遷移-->
        <%= link_to '削除する', form_path(@post.id), data: { turbo: true, turbo_method: :delete } %><!--削除-->
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/forms/index.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.2.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
</head>

<div class="cover-index">
  <div class="container">
    <div class="row ">
      <div class="col d-flex justify-content-center">
        <h1 class="fw-bold text-primary mt-3">投稿一覧</h1>
      </div>
    </div>
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-lg-4 col-md-6 d-flex justify-content-around my-3">
          <div class=" one-post" style="width: 75%; height: 42%;">
          <!--<%= image_tag 'default.png',  class:""%>-->
          <div class="">
            <div class="card text-white bg-info">
              <p class="caption card-title"><%= post.user.name %></p>
              <p class="caption text-center card-title"><%= link_to post.title, "/forms/#{post.id} " %></p>
              <% if post.image %>  <!-- アップロード画像がある場合に実行する -->
                <%post.image.each do |i| %>
                <%= image_tag i.variant(:half), class: "" %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
              <% end %>
              <% end %>
              <p class="caption text-truncate"><%= post.text %></p>
              <p class="caption"><%= "#{post.comments.count} コメント" %></p>
              <p class="caption">
                <%= render post%>
              </p>
            </div>
          </div>
          </div>
        </div>
      <% end %>
      <%#= paginate @posts %>
    </div>
  </div>
</div>



<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="set_center_outer">
        <h2 class="page_title">投稿を作成</h2>
      </div>
      <div class="modal-body">
        <%= render 'forms/new', post: @post %>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/forms/show.html.erb
<div class="cover-show">
  <div class="container">
    <div class="row">
      <h1 class="d-flex justify-content-center mt-5 mb-5">投稿詳細</h1>
    </div>
      <div class="row">  <!-- ユーザー情報を表示 -->
        <div class ="col">
            <% if @post.user != nil %>
            <div class="fs-1"><%= @post.user.name %></div>
          <% end %>
        </div>
      </div>
        <div class="row">
          <% if @post.image_id? %>  <!-- アップロード画像がある場合に実行する -->
            <p class="caption d-flex justify-content-center">
              <%= image_tag @post.image_id.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
            </p>
          <% end %>
        </div>
        <p class="caption d-flex justify-content-center "><%= @post.title %>
          <%= render @post%>
        </p>
        <h2>内容</h2>
        <p id="text"><%= @post.text %></p>
        <% if current_user == @post.user %>
          <%= link_to '編集する', "/forms/#{@post.id}/edit",data: { Turbo: false }, class: "btn btn-info mr-3" %>
        <% end %>
        <%= link_to '投稿一覧ページへ', "/forms", class: "btn btn-dark mt-3" %>



      <div class="comments ml-5 mt-5">
        <%= form_with model: [@post, @comment], url: "/forms/#{@post.id}/comments", local: true do |f| %>
          <%= f.text_area :comment, :size => "60x3", placeholder: "コメントする" %>
          <%= f.submit "送信する", class: "btn btn-success mb-4" %>
        <% end %>

        <p>コメント件数：<%= @comments.count %></p>
        <% @comments.each do |comment| %>
          <div class="comments-index mb-2">
            <%= comment.user.name %>
            <%= comment.created_at.strftime('%Y/%m/%d') %><br>
            <div class="d-flex">
              <%= comment.comment %>
              <% if comment.user == current_user %>
                <div class="comment-delete">
                  <%= button_to "削除", form_comment_path(comment.post, comment), method: :delete, class: "btn-sm btn-danger" %>
                </div>
                </div>
                </div>
              <% end %>
        <% end %>
        <%= paginate @comments %>
      </div>
  </div>
</div>

app/views/homes/home.html.erb
<div class="cover align-middle">
  <div class="text-center">
    <p class="sub-title">〜建築共有のためのSNS〜</p>
    <h1 class="title mb-2">MCC</h1>
    <%= link_to new_user_registration_path do %>
      <h2 class="btn btn-primary mr-2">新規登録</h2>
    <% end %>
    <%= link_to new_user_session_path do %>
      <h2 class="btn btn-success ml-2">ログイン</h2>
    <% end %>
  </div>
</div>

